### ISSUE TITLE
Mention pdflatex as a requirement or dependency?

### ISSUE THREAD

**Issue by quantshah** [johannesjmeyer/rsmf#2]
This is not really an issue for rsmf but related to matplotlib/latex installation. I have a server running Ubuntu where I do most of my work and generate plots. However I never installed LateX there and just used matplotlib to save .pdf files. While trying to run rsmf on the server I got the error:

```
RuntimeError: pdflatex not found.  Install it or change rcParams['pgf.texsystem'] to an available TeX implementation.
```

Maybe it could me mentioned that the package will assume your have a working latex environment.

**Comment by quantshah** [comment]
One liner solution to the issue from (https://gist.github.com/rain1024/98dd5e2c6c8c28f9ea9d):
```
sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
```

**Comment by johannesjmeyer** [comment]
Yes, this is true. I will mention that. The reasoning was that I assumed that `rsmf` is used on the same system as where the LaTeX document is prepared.
