### ISSUE TITLE
Plotting pcolormesh exceeds TeX capacity

### ISSUE THREAD

**Issue by gaborb95** [johannesjmeyer/rsmf#23]
I tried to plot a pcolormesh, but I got the "TeX capacity exceeded, sorry [main memory size=12000000]." error message. I even tried to increase main memory size.
I read that
```
\usepgfplotslibrary{external} 
\tikzexternalize
```
could help, but I can't add it to the code.

**Comment by gaborb95** [comment]
Using lualatex helped! Thanks.

**Comment by johannesjmeyer** [comment]
Okay, that's great! I think the issue is also not with rsmf but with the PGF backend of matplotlib in general.
