### ISSUE TITLE
Incompatible with matplotlib>=3.8

### ISSUE THREAD

**Issue by jwallnoefer** [johannesjmeyer/rsmf#26]
No formatter can be instantiated if matplotlib version is >=3.8

Example:
```
>>> rsmf.setup(r"\documentclass[a4paper,12pt,noarxiv]{quantumarticle}")
OSError: 'seaborn-white' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
```

This seems related to the renaming of the seaborn styles with matplotlib 3.6 https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#seaborn-styles-renamed , which makes this line fail: https://github.com/johannesjmeyer/rsmf/blob/c336cc818d709ccee1c6d3bed3dd524c7dbccca3/rsmf/abstract_formatter.py#L25

**Comment by johannesjmeyer** [comment]
This was fixed in release 0.2.1.
