### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by johannesjmeyer** [johannesjmeyer/rsmf#9]
It would be great to set up Travis or CircleCI to automate the blacking of the code and the unit tests.

**Comment by platipo** [comment]
Hi @johannesjmeyer, have you already configured the repository to work with CircleCI?

**Comment by johannesjmeyer** [comment]
No, I actually haven't set up CI for any project myself, so help with that would be greatly appreciated! I heard that Circle CI is somewhat state of the art right now and it would be cool to have a CI job for the tests (pytest), one for formatting (black) and one for code quality (pylint). Coverage and docs would also be cool. See the checks [in this PR](https://github.com/PennyLaneAI/pennylane/pull/840) in the PennyLane repo for example.

If there's something I have to do as the repo owner just let me know!

**Comment by platipo** [comment]
I'm quite new myself but very intrested in learning CicrleCI and I seized the [Orbtoberfest](https://hacktoberfest.circleci.com/) opportunity  to improve my knowledge.

I think the first steps are:
1. Go to the [CircleCi page](https://circleci.com/)
2. Sign up with your Github account
3. Click "Add projects" menu and then click "Set up Project" on the rsmf project
4. Follow the steps, meanwhile I'll create the PR
